image: alpine:latest

stages:
- build
- publish

before_script:
- npm install

node:10:
  image: node:10-alpine
  stage: build
  script:
  - npm run build
  - npm run we:package
  artifacts:
    paths:
    - public/

publish_firebase:
  image: node:10-alpine
  stage: publish
  only:
  - tags
  script:
  - ls -l public
  - npm run fb:publish -- --token "$FIREBASE_TOKEN"

publish_firefox:
  image: node:10-alpine
  stage: publish
  only:
  - tags
  script:
  - ls -l public
  - npm run we:publish -- --api-key="$JWT_ISSUER" --api-secret="$JWT_SECRET"
