name: Delivery

on:
  push:
    tags:
      - 'v*.*.*'
      - '!v*.*.*-*'

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@tmorin'
      - name: install dependencies
        run: npm ci
      - name: build web-app
        run: npm run wa:build
      - name: build web extension
        run: npm run we:build
      - name: publish web-app
        run: npm run fb:publish
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: publish web-extension
        run: npm run we:package || echo OK
        env:
          WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
          WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}
