name: Delivery

on:
  push:
    tags:
      - 'v*.*.*'
      - '!v*.*.*-*'

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@tmorin'
      - name: Install dependencies
        run: npm ci
      - name: Build web-application
        run: npm run wa:build
      - name: Build web-extention
        run: npm run we:build
      - name: Pack Source code
        run: tar -cvf public/source.tar.gz src scripts .firebaserc .gitignore LICENSE *.json *.md *.js
      - name: Publish web-app
        run: npm run wa:publish
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Publish web-extension
        run: npm run we:publish || echo OK
        env:
          WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
          WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}
      - name: Upload web-application
        uses: actions/upload-artifact@v2
        with:
          name: web-application
          path: public
