name: Integration

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@tmorin'
      - name: Install dependencies
        run: npm ci
      - name: Build web-application
        run: npm run wa:build
      - name: Build web-extention
        run: npm run we:build
      - name: Pack Source code
        run: tar -cvf public/source.tar.gz src scripts .firebaserc .gitignore LICENSE *.json *.md *.js
      - name: Upload web-application
        uses: actions/upload-artifact@v2
        with:
          name: web-application
          path: public
